### ISSUE TITLE
Incompatibility with Gnome Shell 3.36.0

### ISSUE THREAD

**Issue by real-or-random** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#30]
The extension fails to load after an update to Gnome Shell 3.36.0

```
JS ERROR: Extension mprisindicatorbutton@JasonLG1979.github.io: TypeError: imports.gi.Gtk.IconTheme.get_default(...) is null
init@/usr/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/extension.js:32:30
```

It's really weird and somewhat sad to see how extensions break with every release... The maintainer of https://github.com/p-e-w/argos essentially quit because of this.

**Comment by JasonLG1979** [comment]
It's no big deal. I expect the extension to break with every GNOME Shell release, and I have weathered many,lol!!! Sometime I think you almost have to be a bit of a masochist though to be a extension dev. 

3.36 releases tomorrow. I'll fire up something that has 3.36 on my secondary machine (aka the old computer the kids use to watch YouTube) this weekend and see what's going on.

**Comment by coxackie** [comment]
Thanks a lot - waiting for an update to this awesome extension.

**Comment by JasonLG1979** [comment]
Well, turns out it wasn't any one huge or complicated issue, actually it was bunch a little things. I think I have everything sorted though. I will continue to tweak and test what I have though the weekend and at some point if everything checks out I'll push what I have. And then you guys check that out, then I fix anything that needs fix'n, rinse, repeat.

**Comment by coxackie** [comment]
any updates on the 3.36 version?

**Comment by JasonLG1979** [comment]
> any updates on the 3.36 version?

Hold your horses,lol!!! It's coming. It will be dine when it's done.

**Comment by JasonLG1979** [comment]
Should be fixed with https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/commit/501218584191d16b784b5f69b61eeddaabd267b5

**Comment by coxackie** [comment]
testing - seems ok up to now. however, and this may be related to [this](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/issues/10) old issue, chromium MPRIS is still not supported? For example, I can see netflix or spotify web controls in the notifications area of GNOME shell if I disable the extension, but not using the extension.

**Comment by terencode** [comment]
It's working well, just the images are shrinked: 
![image](https://user-images.githubusercontent.com/12665563/77104756-d0a00d00-6a1c-11ea-90a2-be760754e458.png)

**Comment by real-or-random** [comment]
I haven't checked this at all but this reminds me of https://github.com/p-e-w/argos/pull/106

**Comment by JasonLG1979** [comment]
> It's working well, just the images are shrinked

That's a problem with the theme. The cover icon uses the `popup-menu-icon` style class so that the margins line up. In the default and most other themes `popup-menu-icon` sets the icon size and margin some themes however do stupid things with style classes for whatever reason. I'm guessing they set the max-width?

**Comment by JasonLG1979** [comment]
@terencode does 88a8fa2f5331dc5097c556cfa232533ebd93ff25 fix that for you?

**Comment by JasonLG1979** [comment]
> I haven't checked this at all but this reminds me of [p-e-w/argos#106](https://github.com/p-e-w/argos/pull/106)

I'm not sure if this has anything to do with what you're dealing with but if max-height/width is set in the style class then the size will be capped at that size regardless of what you set it to be with `set_size`.

**Comment by JasonLG1979** [comment]
> testing - seems ok up to now. however, and this may be related to [this](https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/issues/10) old issue, chromium MPRIS is still not supported? For example, I can see netflix or spotify web controls in the notifications area of GNOME shell if I disable the extension, but not using the extension.

Yep, chromium/chrome exposes a broken interface.

Also see https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/issues/28

chromium/chrome isn't blacklisted or anything. As soon as they fix their shit it will start working.

**Comment by terencode** [comment]
@JasonLG1979 yes, you are right it's coming from the theme (I'm using Plata) and unfortunately, your last commit doesn't fix it. I'll probably open an issue there.

**Comment by webmastak** [comment]
Do not upgrade to the new version of the gnome immediately after release. It’s better to wait a bit until everything grows together than to suffer from new bugs. ;)

**Comment by JasonLG1979** [comment]
> @JasonLG1979 yes, you are right it's coming from the theme (I'm using Plata) and unfortunately, your last commit doesn't fix it. I'll probably open an issue there.

Then I'll revert it. I am by no means a CSS expert.

**Comment by JasonLG1979** [comment]
> Do not upgrade to the new version of the gnome immediately after release. It’s better to wait a bit until everything grows together than to suffer from new bugs. ;)

I don't really have that option,lol!!!

**Comment by webmastak** [comment]
> I don't really have that option,lol!!!

You, as an extension developer, I understand you. Gnome developers always break backward compatibility with each new version either on purpose or because of their curvature.

**Comment by JasonLG1979** [comment]
> You, as an extension developer, I understand you. Gnome developers always break backward compatibility with each new version either on purpose or because of their curvature.

There's never been a proper API. As far as they're concerned any breakage is in the  implementation details, which by definition are not to be depended upon. That's their rational. Never mind the fact that I'd guess basically no one uses GNOME Shell without any extensions...

**Comment by fdinardo** [comment]
I noticed a stretched icon style while hovering the indicator:
![mpris-indicator-stretch](https://user-images.githubusercontent.com/7387557/77160223-36d17200-6aa7-11ea-958d-62aaa9445e5d.png)
Initially I thought it was related to my theme: icon and shell custom theme. 
But as you can see from the screenshot I changed them to fit the defaults ones and the issue is still there.
this is not a blocking issue, the application works fine, but it's just to let you know.

Thanks for your amazing work!

**Comment by JasonLG1979** [comment]
> I noticed a stretched icon style while hovering the indicator

Yep, that was one of those little things, but I thought I took care of that by manually setting the icon size to 16px?

To be clear the above screenshot is of the current git master? Because I can't reproduce it with the current git master with either Adwaita (the default theme) or Yaru (Ubuntu's default Shell theme).

**Comment by JasonLG1979** [comment]
Going forward though, I think I'm just going to test against those 2 themes to make life easier on myself.

**Comment by fdinardo** [comment]
> To be clear the above screenshot is of the current git master? Because I can't reproduce it with the current git master with either Adwaita (the default theme) or Yaru (Ubuntu's default Shell theme).

No, it's the latest version on gnome-extensions.com, I am going to use your latest git master, and let you know.
Another information I miss before, is that I am running on HIDPI display..
Maybe that is the case....

I'll let you know ASAP about the latest git master.
Thanks

**Comment by JasonLG1979** [comment]
> No, it's the latest version from gnome-extensions.com, I am going to use your latest git master, and let you know.
> Another information I miss before, is that I am running on HIDPI display..
> Maybe that is the case....
> 
> I'll let you know ASAP about the latest git master.
> Thanks

Well this issue is about 3.36 Incompatibility. Running the current git master not on 3.36 will most likely not work very well if at all.

**Comment by fdinardo** [comment]
> Well this issue is about 3.36 Incompatibility. Running the current git master not on 3.36 will most likely not work very well if at all.

You are right, and I am really sorry!
Using the latest master, works like a charm and also this #31 is fixed.

I am really sorry... I don't know why but I was sure that the version from extensions.gnome.com was the latest one.

Thanks for your time.

**Comment by JasonLG1979** [comment]
> I am really sorry... I don't know why but I was sure that the version from extensions.gnome.com was the latest one.

It is the latest release. I just haven't finalized the 3.36 fixes yet. As soon as I do I will update it. If you look there is no 3.36 version up yet.

**Comment by JasonLG1979** [comment]
I pushed a new version to the extensions site. I'm going to close this. If anyone has any other issues please tart a new issue for that specific issue.

**Comment by smathieson** [comment]
Hello, I don't know if this is related, im on debian with 3.36.1, and while things seem to work, clicking does not work. Other extensions seem to be clickable, but Argos is not. Any ideas? Is this a new issue?

**Comment by JasonLG1979** [comment]
@smathieson
> im on debian with 3.36.1, and while things seem to work, clicking does not work.

Debian Testing then?

I don't know what to tell you. I'm running Ubuntu 20.04. Have been since this issue was created. And everything works just fine. What version of the extension are you using? 
 
> Other extensions seem to be clickable, but Argos is not.

This extension has nothing to do with Argos.[ Argos is here.](https://github.com/p-e-w/argos)

**Comment by smathieson** [comment]
Yes, so sorry! Mental mixup! This extension does work on sid :) I am very sorry.

**Comment by JasonLG1979** [comment]
> Yes, so sorry! Mental mixup! This extension does work on sid :) I am very sorry.

It's all good.
